# Generated by Django 2.1 on 2018-08-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0002_auto_20180823_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(max_length=15)),
                ('period', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BillCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('price', models.FloatField()),
                ('call_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calls.EndCall')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='calls',
            field=models.ManyToManyField(to='bills.BillCall'),
        ),
    ]
