# Generated by Django 2.1 on 2018-08-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endcall',
            name='call_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='endcall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='endcall',
            name='type',
            field=models.CharField(default='end', max_length=5),
        ),
        migrations.AlterField(
            model_name='startcall',
            name='call_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='startcall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='startcall',
            name='origin',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='startcall',
            name='type',
            field=models.CharField(default='start', max_length=5),
        ),
    ]
