# Generated by Django 2.1 on 2018-08-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.PositiveIntegerField(db_index=True)),
                ('type', models.CharField(max_length=5)),
                ('timestamp', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StartCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.PositiveIntegerField(db_index=True)),
                ('type', models.CharField(max_length=5)),
                ('timestamp', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
